version: "3.8"

services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle
    hostname: oracle
    restart: always
    ports:
      - "1522:1522"
      - "8080:8080" # Oracle Enterprise Manager HTTP port
    environment:
      ORACLE_SID: XE
      ORACLE_PWD: oracle
      ORACLE_USERNAME: system
      ORACLE_ALLOW_REMOTE: true
    volumes:
      - oradata:/oradata/orcl
    networks:
      - oracle-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - oracle-network
    depends_on:
      - oracle

  oracledb_exporter:
    image: iamseth/oracledb_exporter
    container_name: oracledb_exporter
    ports:
      - "9161:9161"
    environment:
      - DATA_SOURCE_NAME=system/oracle@oracle:1522/XE
    networks:
      - oracle-network
    depends_on:
      - oracle

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - oracle-network
volumes:
  oradata:


networks:
  oracle-network:
    driver: bridge
