global:
  resolve_timeout: 5m

route:
  receiver: 'slack-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'slack-receiver'
    slack_configs:
      - api_url: '${{ secrets.SLACK_WEBHOOK }}' # 복사한 Webhook URL
        channel: '#monitoring' # 알림을 보낼 Slack 채널
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Source:* {{ .GeneratorURL }}
          {{ end }}
          