global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'oracledb_exporter'
    static_configs:
      - targets: ['oracledb_exporter:9161']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alerts.yml'